#*****************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# ov7670_vga_proj.tcl: Tcl script for re-creating project 'ov7670_vga_proj'
#
# Generated by Vivado on Mon Dec 15 01:12:42 CST 2025
# IP Build 6300035 on Fri Nov 14 10:48:45 MST 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (ov7670_vga_proj.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/video/active_stable.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/video/colorbar_gen.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/task/countdown_timer.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/task/debounce_4switches.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/filtering/filter_edge_weighted.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/filtering/filter_blur3x3.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/filtering/filter_gaussian_blur.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/filtering/filter_sobel.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/task/hex7seg_display.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/task/init_status_manager.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/ov7670/ov7670_init.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/ov7670/camera_init_controller.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/ov7670/ov7670_register_table.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/ov7670/ov7670_sccb_master.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/video/video_address_generator.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/task/image_mode_controller.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/video/video_frame_buffer_read.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/video/video_frame_buffer_write.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/video/video_out_manager.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/video/video_out_original.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/video/video_time_generator.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/imports/rtl/top_level.v"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/ip/xilinx_blk_mem_gen_dual/xilinx_blk_mem_gen_dual.xci"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/sources_1/ip/xilinx_clk_wiz_pll_50_25mhz/xilinx_clk_wiz_pll_50_25mhz.xci"
#    "/home/user/Downloads/ov7670_vga_twwang97/ov7670_vga_proj.srcs/constrs_1/imports/constr/sys.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Load modules (relative path)
set script_dir [file dirname [info script]]
source [file join $script_dir tcl/help.tcl]
source [file join $script_dir tcl/config.tcl]
source [file join $script_dir tcl/fileset.tcl]
source [file join $script_dir tcl/project_props.tcl]

# Create project and set properties
create_project $::config::xilinx_proj_name "./$::config::xilinx_proj_name" -part $::config::fpga_part_name
set ::proj_dir [get_property directory [current_project]]
set_project_properties $::proj_dir $::config::xilinx_proj_name $::config::fpga_part_name $::config::default_lib

# sources_1
set fs_sources [ensure_and_import_vhdl2008_fileset sources_1 -srcset $::files::vhdl_rel_files]
safe_set_property "top" $::config::top_source_name $fs_sources

# import IP file and set its properties
import_ip_into_sources $fs_sources $::files::ip_file
import_ip_into_sources $fs_sources $::files::ip_file2

# constrs_1
set fs_constrs [ensure_and_import_fileset constrs_1 -constrset [list $::files::xdc_file]]
safe_set_property "target_part" $::config::fpga_part_name $fs_constrs

# sim_1
set fs_sim [ensure_and_import_vhdl2008_fileset sim_1 -simset [list $::files::tb_file]]
safe_set_property "sim_wrapper_top" "1" $fs_sim
safe_set_property "top" $::config::top_tb_name $fs_sim
safe_set_property "top_lib" $::config::default_lib $fs_sim

update_compile_order -fileset sources_1